### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kalmarek** [kalmarek/KnuthBendix.jl#65]
@RearrangedLetters 
- [ ] Create text-file interface for kbmag (e.g. from https://github.com/bprzybylski/KBmag.jl/blob/master/src/BinWrapper.jl)
- [ ] fixed set of benchmarks (easy = <2s, medium = <30s, hard = Inf) to compare
- [ ] try running the same examples with KnuthBendix.jl and collect timing
- [ ] identify the bottlenecks (profiling etc.)
